"""add pin_code to admin_regions

Revision ID: 1a3ee76e70e0
Revises: c695b2b41fee
Create Date: 2026-07-06 11:22:40.727807+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3ee76e70e0'
down_revision: Union[str, None] = 'c695b2b41fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_regions', sa.Column('pin_code', sa.String(length=20), nullable=True))
    op.execute("UPDATE admin_regions SET pin_code = 'PIN-' || substring(name from 1 for 10) || '-' || substring(id::text from 1 for 4)")
    op.alter_column('admin_regions', 'pin_code', nullable=False)
    op.create_index(op.f('ix_admin_regions_pin_code'), 'admin_regions', ['pin_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_regions_pin_code'), table_name='admin_regions')
    op.drop_column('admin_regions', 'pin_code')
    # ### end Alembic commands ###
