"""add_aadhar_and_suggestions

Revision ID: 9e27d72c3fc8
Revises: a1b2c3d4e5f6
Create Date: 2026-07-11 14:15:47.972484+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e27d72c3fc8'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('suggestion', 'bug_report', name='suggestion_type'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_chat_sender_receiver_created', table_name='chat_messages')
    op.drop_index('ix_connection_requests_receiver', table_name='connection_requests')
    op.drop_index('ix_connection_requests_sender', table_name='connection_requests')
    op.drop_index('ix_connection_requests_status', table_name='connection_requests')
    op.drop_index('ix_matrimony_opted_in', table_name='matrimony_profiles')
    op.drop_index('ix_memorial_date_of_death', table_name='memorial_records')
    op.drop_index('ix_profiles_family_unit_id', table_name='profiles')
    op.drop_index('ix_profiles_full_name', table_name='profiles')
    op.add_column('users', sa.Column('aadhar_number', sa.String(length=12), nullable=True))
    op.add_column('users', sa.Column('aadhar_card_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('aadhar_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('aadhar_data_delete_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_aadhar_number'), 'users', ['aadhar_number'], unique=False)
    op.create_unique_constraint('uq_approval_per_admin', 'verification_approvals', ['verification_request_id', 'approver_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_approval_per_admin', 'verification_approvals', type_='unique')
    op.drop_index(op.f('ix_users_aadhar_number'), table_name='users')
    op.drop_column('users', 'aadhar_data_delete_at')
    op.drop_column('users', 'aadhar_verified_at')
    op.drop_column('users', 'aadhar_card_url')
    op.drop_column('users', 'aadhar_number')
    op.create_index('ix_profiles_full_name', 'profiles', ['full_name'], unique=False)
    op.create_index('ix_profiles_family_unit_id', 'profiles', ['family_unit_id'], unique=False)
    op.create_index('ix_memorial_date_of_death', 'memorial_records', ['date_of_death'], unique=False)
    op.create_index('ix_matrimony_opted_in', 'matrimony_profiles', ['opted_in'], unique=False)
    op.create_index('ix_connection_requests_status', 'connection_requests', ['status'], unique=False)
    op.create_index('ix_connection_requests_sender', 'connection_requests', ['sender_profile_id'], unique=False)
    op.create_index('ix_connection_requests_receiver', 'connection_requests', ['receiver_profile_id'], unique=False)
    op.create_index('ix_chat_sender_receiver_created', 'chat_messages', ['sender_profile_id', 'receiver_profile_id', 'created_at'], unique=False)
    op.drop_table('suggestions')
    # ### end Alembic commands ###
