"""fix email verification code column length

Revision ID: dda73a30d479
Revises: abc123def456
Create Date: 2026-07-12 09:44:48.470827+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda73a30d479'
down_revision: Union[str, None] = 'abc123def456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_verifications', 'code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_verifications', 'code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
