"""create_chat_messages

Revision ID: 9db65195565c
Revises: c3f1a8b92e44
Create Date: 2026-07-11 06:07:34.202721+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db65195565c'
down_revision: Union[str, None] = 'c3f1a8b92e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_profile_id', sa.UUID(), nullable=False),
    sa.Column('receiver_profile_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_receiver_profile_id'), 'chat_messages', ['receiver_profile_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_profile_id'), 'chat_messages', ['sender_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_chat_messages_sender_profile_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_receiver_profile_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
