"""add_co_approver_approval_to_matrimony

Revision ID: c695b2b41fee
Revises: 0178e2aaa6ca
Create Date: 2026-07-04 07:58:11.396189+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c695b2b41fee'
down_revision: Union[str, None] = '0178e2aaa6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrimony_profiles', sa.Column('family_co_approver_approved', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matrimony_profiles', 'family_co_approver_approved')
    # ### end Alembic commands ###
