"""add_username_to_profiles

Revision ID: 0178e2aaa6ca
Revises: 043f8ab9cd77
Create Date: 2026-07-04 07:23:51.972467+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0178e2aaa6ca'
down_revision: Union[str, None] = '043f8ab9cd77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('username', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_column('profiles', 'username')
    # ### end Alembic commands ###
