"""add sub_caste and company

Revision ID: 1d4b776139cd
Revises: 9db65195565c
Create Date: 2026-07-11 07:07:54.516790+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4b776139cd'
down_revision: Union[str, None] = '9db65195565c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matrimony_profiles', sa.Column('sub_caste', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('company_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matrimony_profiles', 'company_name')
    op.drop_column('matrimony_profiles', 'sub_caste')
    # ### end Alembic commands ###
