"""add_region_id_to_profile

Revision ID: 94624cc39623
Revises: 1a3ee76e70e0
Create Date: 2026-07-06 12:42:46.282436+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94624cc39623'
down_revision: Union[str, None] = '1a3ee76e70e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('region_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'admin_regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'region_id')
    # ### end Alembic commands ###
