"""comprehensive_account_and_matrimony

Revision ID: 032d97cc0f66
Revises: 2026_06_30_000000
Create Date: 2026-07-01 12:28:12.036854+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '032d97cc0f66'
down_revision: Union[str, None] = '2026_06_30_000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=True)
    op.drop_constraint('admin_regions_name_key', 'admin_regions', type_='unique')
    op.create_index(op.f('ix_admin_regions_name'), 'admin_regions', ['name'], unique=True)
    op.drop_index('idx_connection_requests_receiver', table_name='connection_requests')
    op.drop_index('idx_connection_requests_sender', table_name='connection_requests')
    op.add_column('matrimony_profiles', sa.Column('height_cm', sa.String(length=10), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('body_type', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('complexion', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('highest_qualification', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('field_of_study', sa.String(length=255), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('institution', sa.String(length=255), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('employment_type', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('job_title', sa.String(length=255), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('income_range', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('work_location', sa.String(length=255), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('gotra', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('rashi', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('nakshatra', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('manglik_status', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('birth_time', sa.String(length=20), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('birth_place', sa.String(length=255), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('father_name', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('father_occupation', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('mother_name', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('mother_occupation', sa.String(length=100), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('brothers_count', sa.String(length=10), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('brothers_marital_status', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('sisters_count', sa.String(length=10), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('sisters_marital_status', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('family_type', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('family_values', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('family_financial_status', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('diet', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('smoking', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('drinking', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('physical_activity', sa.String(length=50), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('additional_photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('matrimony_profiles', sa.Column('visibility', sa.String(length=50), nullable=True))
    op.alter_column('matrimony_profiles', 'hobbies',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="'[]'::jsonb")
    op.drop_index('idx_matrimony_active_profiles', table_name='matrimony_profiles', postgresql_where='(opted_in = true)')
    op.drop_index('idx_matrimony_preferences', table_name='matrimony_profiles', postgresql_using='gin')
    op.drop_column('matrimony_profiles', 'education')
    op.drop_column('matrimony_profiles', 'family_background')
    op.drop_index('idx_memorial_records_profile_id', table_name='memorial_records')
    op.drop_index('idx_profiles_active_members', table_name='profiles', postgresql_where='(is_memorial = false)')
    op.drop_index('idx_profiles_family_unit_id', table_name='profiles')
    op.drop_index('idx_profiles_name_trgm', table_name='profiles', postgresql_using='gin')
    op.drop_index('idx_profiles_user_id', table_name='profiles')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.execute("UPDATE users SET email = 'user_' || id || '@communityconnect.org' WHERE email IS NULL")
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.execute("UPDATE users SET password_hash = 'dummy_hash' WHERE password_hash IS NULL")
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_index('idx_verification_approvals_req_id', table_name='verification_approvals')
    op.drop_index('idx_verification_requests_target', table_name='verification_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_verification_requests_target', 'verification_requests', ['target_user_id'], unique=False)
    op.create_index('idx_verification_approvals_req_id', 'verification_approvals', ['verification_request_id'], unique=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_phone', 'users', ['phone_number'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.create_index('idx_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_index('idx_profiles_name_trgm', 'profiles', ['full_name'], unique=False, postgresql_using='gin')
    op.create_index('idx_profiles_family_unit_id', 'profiles', ['family_unit_id'], unique=False)
    op.create_index('idx_profiles_active_members', 'profiles', ['id'], unique=False, postgresql_where='(is_memorial = false)')
    op.create_index('idx_memorial_records_profile_id', 'memorial_records', ['profile_id'], unique=False)
    op.add_column('matrimony_profiles', sa.Column('family_background', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('matrimony_profiles', sa.Column('education', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('idx_matrimony_preferences', 'matrimony_profiles', ['preferences'], unique=False, postgresql_using='gin')
    op.create_index('idx_matrimony_active_profiles', 'matrimony_profiles', ['profile_id'], unique=False, postgresql_where='(opted_in = true)')
    op.alter_column('matrimony_profiles', 'hobbies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('matrimony_profiles', 'visibility')
    op.drop_column('matrimony_profiles', 'additional_photos')
    op.drop_column('matrimony_profiles', 'languages')
    op.drop_column('matrimony_profiles', 'physical_activity')
    op.drop_column('matrimony_profiles', 'drinking')
    op.drop_column('matrimony_profiles', 'smoking')
    op.drop_column('matrimony_profiles', 'diet')
    op.drop_column('matrimony_profiles', 'family_financial_status')
    op.drop_column('matrimony_profiles', 'family_values')
    op.drop_column('matrimony_profiles', 'family_type')
    op.drop_column('matrimony_profiles', 'sisters_marital_status')
    op.drop_column('matrimony_profiles', 'sisters_count')
    op.drop_column('matrimony_profiles', 'brothers_marital_status')
    op.drop_column('matrimony_profiles', 'brothers_count')
    op.drop_column('matrimony_profiles', 'mother_occupation')
    op.drop_column('matrimony_profiles', 'mother_name')
    op.drop_column('matrimony_profiles', 'father_occupation')
    op.drop_column('matrimony_profiles', 'father_name')
    op.drop_column('matrimony_profiles', 'birth_place')
    op.drop_column('matrimony_profiles', 'birth_time')
    op.drop_column('matrimony_profiles', 'manglik_status')
    op.drop_column('matrimony_profiles', 'nakshatra')
    op.drop_column('matrimony_profiles', 'rashi')
    op.drop_column('matrimony_profiles', 'gotra')
    op.drop_column('matrimony_profiles', 'work_location')
    op.drop_column('matrimony_profiles', 'income_range')
    op.drop_column('matrimony_profiles', 'job_title')
    op.drop_column('matrimony_profiles', 'employment_type')
    op.drop_column('matrimony_profiles', 'institution')
    op.drop_column('matrimony_profiles', 'field_of_study')
    op.drop_column('matrimony_profiles', 'highest_qualification')
    op.drop_column('matrimony_profiles', 'complexion')
    op.drop_column('matrimony_profiles', 'body_type')
    op.drop_column('matrimony_profiles', 'height_cm')
    op.create_index('idx_connection_requests_sender', 'connection_requests', ['sender_profile_id'], unique=False)
    op.create_index('idx_connection_requests_receiver', 'connection_requests', ['receiver_profile_id'], unique=False)
    op.drop_index(op.f('ix_admin_regions_name'), table_name='admin_regions')
    op.create_unique_constraint('admin_regions_name_key', 'admin_regions', ['name'])
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
